[package]
name = "aqueduct"
version = "0.2.1"
edition = "2018"
authors = ["Zerthox <zerthox@gmail.com>"]
description = "Pipeline interface for chaining operations"
homepage = "https://github.com/zerthox/aqueduct"
repository = "https://github.com/zerthox/aqueduct"
license = "MIT"
